In [1]:
import pandas as pd

In [5]:
films = pd.read_csv("../veri_seti/imdb_1000.csv")
films

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [6]:
films.columns

Index(['star_rating', 'title', 'content_rating', 'genre', 'duration',
       'actors_list'],
      dtype='object')

In [8]:
films["title"].head()

0    The Shawshank Redemption
1               The Godfather
2      The Godfather: Part II
3             The Dark Knight
4                Pulp Fiction
Name: title, dtype: object

In [9]:
films.title.head(5)

0    The Shawshank Redemption
1               The Godfather
2      The Godfather: Part II
3             The Dark Knight
4                Pulp Fiction
Name: title, dtype: object

In [16]:
films[["title", "star_rating"]].head()

                      title  star_rating
0  The Shawshank Redemption          9.3
1             The Godfather          9.2
2    The Godfather: Part II          9.1
3           The Dark Knight          9.0
4              Pulp Fiction          8.9

In [15]:
films[:9][["title", "star_rating"]]

                                           title  star_rating
0                       The Shawshank Redemption          9.3
1                                  The Godfather          9.2
2                         The Godfather: Part II          9.1
3                                The Dark Knight          9.0
4                                   Pulp Fiction          8.9
5                                   12 Angry Men          8.9
6                 The Good, the Bad and the Ugly          8.9
7  The Lord of the Rings: The Return of the King          8.9
8                               Schindler's List          8.9

In [24]:
films[(films["star_rating"] > 8.5)][["title", "star_rating"]]

                                                title  star_rating
0                            The Shawshank Redemption          9.3
1                                       The Godfather          9.2
2                              The Godfather: Part II          9.1
3                                     The Dark Knight          9.0
4                                        Pulp Fiction          8.9
5                                        12 Angry Men          8.9
6                      The Good, the Bad and the Ugly          8.9
7       The Lord of the Rings: The Return of the King          8.9
8                                    Schindler's List          8.9
9                                          Fight Club          8.9
10  The Lord of the Rings: The Fellowship of the Ring          8.8
11                                          Inception          8.8
12     Star Wars: Episode V - The Empire Strikes Back          8.8
13                                       Forrest Gump          8.8
14              The Lord of the Rings: The Two Towers          8.8
15                                       Interstellar          8.7
16                    One Flew Over the Cuckoo's Nest          8.7
17                                      Seven Samurai          8.7
18                                         Goodfellas          8.7
19                                          Star Wars          8.7
20                                         The Matrix          8.7
21                                        City of God          8.7
22                              It's a Wonderful Life          8.7
23                                 The Usual Suspects          8.7
24                                              Se7en          8.7
25                                  Life Is Beautiful          8.6
26                       Once Upon a Time in the West          8.6
27                           The Silence of the Lambs          8.6
28                             Leon: The Professional          8.6
29                                        City Lights          8.6
30                                      Spirited Away          8.6
31                                   The Intouchables          8.6
32                                         Casablanca          8.6
33                                           Whiplash          8.6
34                                 American History X          8.6
35                                       Modern Times          8.6
36                                Saving Private Ryan          8.6
37                            Raiders of the Lost Ark          8.6
38                                        Rear Window          8.6
39                                             Psycho          8.6

In [32]:
films[(films["star_rating"] > 8.5)  &(
    films["star_rating"] < 9)][["title", "star_rating"]]

                                                title  star_rating
4                                        Pulp Fiction          8.9
5                                        12 Angry Men          8.9
6                      The Good, the Bad and the Ugly          8.9
7       The Lord of the Rings: The Return of the King          8.9
8                                    Schindler's List          8.9
9                                          Fight Club          8.9
10  The Lord of the Rings: The Fellowship of the Ring          8.8
11                                          Inception          8.8
12     Star Wars: Episode V - The Empire Strikes Back          8.8
13                                       Forrest Gump          8.8
14              The Lord of the Rings: The Two Towers          8.8
15                                       Interstellar          8.7
16                    One Flew Over the Cuckoo's Nest          8.7
17                                      Seven Samurai          8.7
18                                         Goodfellas          8.7
19                                          Star Wars          8.7
20                                         The Matrix          8.7
21                                        City of God          8.7
22                              It's a Wonderful Life          8.7
23                                 The Usual Suspects          8.7
24                                              Se7en          8.7
25                                  Life Is Beautiful          8.6
26                       Once Upon a Time in the West          8.6
27                           The Silence of the Lambs          8.6
28                             Leon: The Professional          8.6
29                                        City Lights          8.6
30                                      Spirited Away          8.6
31                                   The Intouchables          8.6
32                                         Casablanca          8.6
33                                           Whiplash          8.6
34                                 American History X          8.6
35                                       Modern Times          8.6
36                                Saving Private Ryan          8.6
37                            Raiders of the Lost Ark          8.6
38                                        Rear Window          8.6
39                                             Psycho          8.6

In [36]:
films.query("star_rating >= 9.0 | star_rating == 8.5")[["title","star_rating"]]

                                                title  star_rating
0                            The Shawshank Redemption          9.3
1                                       The Godfather          9.2
2                              The Godfather: Part II          9.1
3                                     The Dark Knight          9.0
40                                     The Green Mile          8.5
41                                       Sunset Blvd.          8.5
42                                        The Pianist          8.5
43                              The Dark Knight Rises          8.5
44                                          Gladiator          8.5
45                         Terminator 2: Judgment Day          8.5
46                                            Memento          8.5
47                                   Taare Zameen Par          8.5
48  Dr. Strangelove or: How I Learned to Stop Worr...          8.5
49                                       The Departed          8.5
50                                    Cinema Paradiso          8.5
51                                     Apocalypse Now          8.5
52                                 The Great Dictator          8.5
53                                       The Prestige          8.5
54                                 Back to the Future          8.5
55                                      The Lion King          8.5
56                                The Lives of Others          8.5
57                                              Alien          8.5
58                                     Paths of Glory          8.5
59                                   Django Unchained          8.5
60                                           3 Idiots          8.5
61                             Grave of the Fireflies          8.5
62                                        The Shining          8.5